config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('order/', include('order.urls')),
    path('twitter/', include('twitter_social.urls')),
    path('device_management/', include('device_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

device_management/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "device_management"

urlpatterns = [
    path('', views.device1, name='device1'),
    path('mypage',views.mypage, name='mypage'),
    path('control',views.control, name='control'),
    path('device',views.device, name='device'),
    path('device1', views.device1, name='device1'),
    path('device2', views.device2, name='device2'),
    path('device3', views.device3, name='device3'),
    path('device4', views.device4, name='device4'),
    path('device6', views.device6, name='device6'),

    path('device7', views.device7, name='device7'),
    path('create_plant_params', views.create_plant_params.as_view(), name='create_plant_params'),
    path('create_farm_info', views.create_farm_info.as_view(), name='Create_farm_info'),
    path('crop_info_registeration', views.crop_info_registeration.as_view(), name='crop_info_registeration'),

    path('status/<int:pk>', views.status, name='status'),

    path('my_page', views.mypage_status, name='my_page'),
    #path('crop_info_reg/<int:farm_info>', views.crop_info_reg_f, name='crop_info_reg'),
    path('crop_info_reg', views.crop_info_reg_f, name='crop_info_reg'),
    path('history_detail/<int:device_serial>/<int:farm_id>/<int:plant_id>',views.history_detail, name='history_detail'),
    
    path('device_control/<int:device_serial>/<int:farm_id>', views.goto_control_device, name="device_control"),
    path('send_action', views.GET_Interface_To_Device_Manual.as_view(), name="send_action"),
    path('catch_flying_status', views.get_mock_plant_status.as_view(), name="catch_flying_status"),
    path('compare', views.compare_currentState_with_default.as_view(), name="compare"),
    path('store_default_status',views.Store_Default_Status.as_view(), name="store_default_status"),
]

order/urls.py
from django.urls import path
from . import views
from .views import OrderCreate, AddCart, modify_cart

urlpatterns = [
    path('create/', OrderCreate.as_view()),
    path('addcart/', AddCart.as_view()),
    path('complete/',OrderCreate.as_view(), name='ordercomplete'),
    path('orderlist/<int:pk>',views.order_list, name='order_list'),
    path('cart/<int:pk>',views.cart_list, name='cartlist'),
    path('cart/modify/<int:pk>', views.modify_cart,name='modifycart'),
    path('payment/',views.payment, name='payment'),
    path('payment/complete',views.cart_to_buy, name='cartbuy')
]

device_management/forms.py
from django import forms
from .models import Device_Info, Farm_Info, Growth_Params

class Device_Form(forms.ModelForm):
    class Meta:
        model = Device_Info
        fields = "__all__"

class Farm_Info_Form(forms.ModelForm):
    class Meta: 
        model = Farm_Info
        fields = "__all__"

class Growth_Params_Form(forms.ModelForm):
    class Meta:
        model = Growth_Params
        fields = ['germination_time', 'seeding_ec', 'ec', 'progress_date', 'temparature', 'ph', 'humidity','light_hr',
                  'nutrientA', 'nutrientB', 'nutrientC', 'nutrientD', 'light_lux', 'do', 'co2']

device_management/views.py
from functools import partial
from django.http.response import Http404
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.core import serializers
from rest_framework.serializers import Serializer
# Create your views here.

from .models import Default_Status, Device_Info, Farm_Info, Growth_Params, Plant_Info, mock_params, Device_Interface 
from rest_framework import viewsets
from rest_framework.generics import CreateAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import Default_Status_Serializer, GET_MOCK_Interface, POST_Growth_Param_Serializer, POST_Mock, POST_Farm_Info, POST_Plant_Info, Serial_Interface
from .forms import Farm_Info_Form,Growth_Params_Form
import json
from django.views.decorators.csrf import csrf_exempt
from .status_default import Status_Default
#from .handling_excel import Default_Status_Handler


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def control(request):
    return render(request, 'device_management/control.html')

def mypage(request):
    user = request.user
    try:
        #Bug occurred : When use Device more than 2 devices...
        device_info = Device_Info.objects.filter(device_user=user)[0]
    except:
        return redirect('device_management:device1')
    print(device_info.device_serial)
    farm_list = Farm_Info.objects.filter(device_info=device_info)
    print(farm_list)
    farm_dict = {}

    '''to handle Left date and Left light_hr for each plant, send default status data to mypage.html -> later... 
    default_status_dict = {}
    default_status_querySet = Default_Status.objects.all()
    for df_stat in default_status_querySet:
    
    현재,  mypage.html에서 form을 iterate하면서 ui를 만드는데, 이게 farm, growth param을 여러 개 던져서 굴리면서 만들어짐.
    각각의 growth param에서의 left time값과 default로 정해진 harvesttime, light_hr과 각각 차이를 구해서 각각의 farm마다 전해주어야 하는데
    문제는, 이미 각 farm마다 grow_param을 종속 시켜서 던져주고 있는 상황, 클래스를 새로 생성해서 던져주는 것이 아니라면..
    html의 {{}}내에선 []를 통한 인덱싱도 안되고 내부에서 사칙연산도 불가능. 오직 .를 이용하여 클래스 멤버만 접근이 가능하므로 
    1.이미 계산된 값을 같이 엮어서 던져주거나
    2.자바스크립트로 따로 데이터를 빼서 계산한 뒤 동적으로 DOM에 할당한다.
    1.의 경우 이미 farm_dict[farm] = grow_param()으로 엮여있고 여기에 grow_param + left time 형태로 정보를 넘겨주어야 함
    2.의 경우, {{for}}를 이용해 DOM을 django template에서 자동생성하므로 모든 DOM을 JS로 동적생성시키는 방식으로 바꿔야 함.

    '''

    for farm in farm_list:
        plant = Plant_Info.objects.get(farm_info=farm)
        grow_param = Growth_Params.objects.filter(plant_info=plant)

        if grow_param:
            farm_dict[farm] = grow_param[len(grow_param)-1]#not allow negative indexing
        else:
            farm_dict[farm] = None
    print(farm_dict)
    return render(request, 'device_management/mypage.html', {'farm_list': farm_dict})

# has to fix when Device data is exist, move to control.html, not exists, move to device1.html
# In this time, just get data from html3, device_serial, device_name.
def device(request):
    device_information = Device_Info.objects.all()
    print(request.user)
    print(device_information)
    try :
        device_information = Device_Info.objects.create(
            device_user = request.user,
            device_serial = request.GET.get("device_serial"), \
            device_detail = request.GET.get("detail"), \
            device_model = request.GET.get("modelno"), \
            device_name = request.GET.get("device_name"),\
            device_ip_address = request.GET.get("ip_address"), \
            device_password = request.GET.get("password"))
    except Exception as ex:
        device_information = None
        print("EXCEPTION----------------------------device_info store", ex)

    context = {'device_info': device_information} #send information to html file!
    return render(request, 'device_management/device4.html', context = context)

def device1(request):
    return render(request, 'device_management/device1.html')

def device2(request):


    return render(request, 'device_management/device2.html')

def device3(request):
    return render(request, 'device_management/device3.html')

def device4(request):
    try:
        device_info = Device_Info.objects.filter(device_user=request.user)[0]
        return render(request, 'device_management/device4.html', {'device_info': device_info})
    except:
        return redirect('device_management:device1')

def device6(request):
    return render(request, 'device_management/device6.html')



def device7(request):
    #device_info_serial = request.POST['device_info'].get("device_serial")
    
    device_serial = request.POST.get('device_serial') #changed way to send and receive only device_serial value not device_info object
    #context = {'device_serial': device_info_serial} #send information to html file!

    
    context = {'device_serial': device_serial}
    print(device_serial)
    return render(request, 'device_management/device7.html', context=context)


def farm_info_setting(request):
    mock_farm_info = {
        "device_info"
    }

def status(request, pk):
    device_info = Device_Info.objects.filter(device_user=request.user)[0]
    farm = Farm_Info.objects.get(id=pk)
    plant = Plant_Info.objects.get(farm_info=farm)
    grow_param = Growth_Params.objects.filter(plant_info=plant)
    default_status = Default_Status.objects.get(crop_name = plant.crop_name)
    harvest_time = default_status.harvesting_time
    

    if request.method == 'POST':
        form = Growth_Params_Form(request.POST)
        if form.is_valid():
            param = form.save(commit=False)
            param.device_info = device_info
            param.plant_info = plant
            param.date = timezone.now()
            param.save()
            print(param)
        #Growth_Params.objects.create(
        #    device_info = device_info,
        #    plant_info = plant,#already exist data
        #    germination_time = request.data["germination_time"],
        #    seeding_ec = request.data["seeding_ec"],
        #    ec = request.data["ec"],
        #    progress_date=request.data["progress_date"],
        #    temparature=request.data["temparature"],
        #    ph=request.data["ph"],
        #    humidity=request.data["humidity"],
        #    date=timezone.now(),#already exist
        #    light_hr=request.data["light_hr"],
        #)
    if grow_param:
        grow_param = grow_param[len(grow_param) - 1]
        rest_days = harvest_time - grow_param.progress_date
    else:
        grow_param = None
        rest_days = -1
    return render(request, 'device_management/status.html', {'farm':farm,
                                                             'plant':plant,
                                                             'grow_param': grow_param,
                                                             'device_info': device_info, 
                                                             'rest_days':rest_days})

def mypage_status(request):
    return render(request, 'device_management/mypage.html')


def history_detail(request, device_serial, farm_id, plant_id):
    '''
    if request.method == 'GET':
        device_serial = request.GET['device_info']
    ''' 
    
    # Not Model object, Response(recent 10 status values) from ClassView
    status = get_mock_plant_status.get(get_mock_plant_status, request, device_serial, plant_id)

    farm_info = Farm_Info.objects.get(pk=farm_id)
    plant_info = Plant_Info.objects.get(pk = plant_id)
    device_info = Device_Info.objects.get(pk = device_serial)

    #Add Default Status data, for serialize function it should use QuerySet Object, Not Model Class object...
    default_status = Default_Status.objects.filter(crop_name = plant_info.crop_name)
    print(type(default_status))
    #for serialize function it should use QuerySet Object, Not Model Class object...
    default_status_serialized = serializers.serialize('json', default_status)

    return render(request, 'device_management/history_detail.html', {"status":status.data, "device_info":device_info,\
        "farm_info":farm_info, "plant_info":plant_info, "default_status":default_status_serialized })

class crop_info_registeration(APIView):
    def post(self, request):
        print(request.data)
        crop_serializer = POST_Plant_Info(data = request.data)
        
        if crop_serializer.is_valid():
            crop_serializer.save()
            crop_id = crop_serializer.data["id"]
            crop_info = Plant_Info.objects.get(id=crop_id)
            return redirect('device_management:status', pk=request.data["farm_info"])
        return Response(crop_serializer.errors, status=400)


@csrf_exempt
def crop_info_reg_f(request):
    if request.method == 'POST':
        farm_info_id = int(request.POST['farm_info'])
        print(farm_info_id)
        farm_info_inst = Farm_Info.objects.get(pk=farm_info_id)
        print(farm_info_inst.farm_name)
        crop_group = request.POST['crop_group']
        crop_name = request.POST['crop_name']
        life_stage = request.POST['life_stage']
        planting_date = request.POST['planting_date']

    elif request.method == 'GET':
        farm_info_id = int(request.GET.get('farm_info'))
        print(farm_info_id)
        farm_info_inst = Farm_Info.objects.get(pk=farm_info_id)
        crop_group = request.GET.get('crop_group')
        crop_name = request.GET.get('crop_name')
        life_stage = request.GET.get('life_stage')
        planting_date = request.GET.get('planting_date')

    print("plant info: "+crop_group, crop_name,life_stage,planting_date)
    plant_information = Plant_Info.objects.all()
    
    try :
        plant_information = Plant_Info(farm_info = farm_info_inst, \
            crop_group =crop_group , \
            crop_name = crop_name, \
            life_stage = life_stage,\
            planting_date = planting_date, \
            )
        plant_information.save()

device_management/templates/device_management/device1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>
    <!-- device -->
    <div class="device_wrap footer_on">
        <div class="cont tx_c tm88">
            <img src={% static "images/img_main.png" alt="main image" %}>
            <h1 class=" bold title">No Device Yet</h1>
            <p class="sub_txt">Add device to start smart farming<br>at your home without any mess.</p>
        </div>
        
        <button type="button" class="arrow_btn">
            <a href = {% url 'device_management:device3' %}>
            <span class="">Connect smart device</span></a>
            <img src={% static "images/ic_arrow.png" alt="arrow icon" %}>
    
        </button>
    </div>
    <!-- //device -->
</body>
{% endblock %}

device_management/templates/device_management/device10.html
{% extends 'base_back.html' %}
{% load static %}
{% block content %}
<body>
    <!-- device -->
    <div class="device_wrap footer_on">
        <form action="">
            <div class="cont tx_c tm88">
                <img src={% static "images/img_farm.png" %} alt="farm image">
                <h1 class=" bold title bp20">Choose a name for your farm</h1>
                <div class="input_type1">
                    <input type="text" placeholder="Lettuce Garden" class="tx_l">
                </div>
                <a href="#" class="next_btn tm76 re_tm10">Next</a>
            </div>
        </form>
    </div>
    <!-- //device -->
</body>
{% endblock %}

device_management/templates/device_management/device11.html
{% extends 'base_back.html' %}
{% load static %}
{% block content %}
<body>
    <!-- device -->
    <div class="device_wrap footer_on">
        <form action="">
            <div class="cont tx_c tm88">
                <img src={% static "images/img_plants.png" %} alt="plants image">
                <h1 class=" bold title bp0">Total number of plants</h1>
                <div class="choice_box choice_box2">
                    <p>50</p>
                    <div class="btn_box">
                        <button type="button"><img src={% static "images/ic_up.png" %} alt="up arrow icon"></button>
                        <button type="button" class="tm6"><img src={% static "images/ic_down.png" %} alt="down arrow icon"></button>
                    </div>
                </div>
                <a href="#" class="next_btn tm86 re_tm10">Next</a>
            </div>
        </form>
    </div>
    <!-- //device -->
</body>
{% endblock %}

device_management/templates/device_management/device2.html
{% extends 'base_back.html' %}
{% load static %}
{% block content %}
<body>
    <!-- device -->
    <div class="device_wrap footer_on">
        <div class="cont tx_c">
            <h2 class="top_title">Select your Farm</h2>
            <button type="button" class="new_btn tm50">Create new farm</button>
            <h1 class=" bold title bp10">No Farm Yet</h1>
            <p class="sub_txt">Create new farm to start !</p>
            <p class="sub_txt tm20">If you have Krishian Smart grow kit <br>
                Select it from below option</p>
        </div>
        <button type="button" class="arrow_btn tm34">
            <span class="">Choose Krishian smart grow kit</span>
            <img src={% static "images/ic_arrow.png" alt="arrow icon" %}>
        </button>
    </div>
</body>
{% endblock %}

device_management/templates/device_management/device3.html
{% extends 'base_back.html' %}
{% load static %}
{% block content %}

<script type="text/javascript">
    window.onload = function(){

        let ipformat = /^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/;
        let serialformat = /^([0-9]){15}$/;
        let reg_button = document.getElementById("device_register");
        reg_button.addEventListener('click', function(){
            let ip_addr = document.getElementsByName("ip_address")[0].value;
            let serialnumber = document.getElementsByName("device_serial")[0].value;


            console.log(ipformat.test(ip_addr));
            console.log(serialformat.test(serialnumber));
            if (!ipformat.test(ip_addr)){
                alert("Wrong Format for IP Address!!");
            }
            if (!serialformat.test(serialnumber)){
                alert("SerialNumber must be 15 digits!!");
            }

            if(ipformat.test(ip_addr) && serialformat.test(serialnumber)){
                document.getElementsByTagName("form")[0].submit();
            }
        });
    }
</script>

<body>
    <div class="device_wrap footer_on tp140 re_tp10">
        <form action={% url 'device_management:device' %}>
            {% csrf_token %}
            <div class="cont tx_c">
                <h2 class="top_title tp0">Device details</h2>
                <p class="sub_txt tm25"><span class="sub_txt txt_medium">Model No : </span>SMG01</p>
                <p class="sub_txt tp6"><span class="sub_txt txt_medium">Device details : </span>Smart Grow</p>
                <ul class="tm50">
                    <li class="input_type1">
                        <input type="text" name="ip_address" placeholder="IP ADDRESS : XXX.XXX.XXX.XXX">
                    </li>
                    <li class="input_type1 tm10">
                        <input type="password" name="password" placeholder="PASSWORD">
                    </li>
                    <li class="input_type1 tm10">
                        <input type="text" name="device_serial" placeholder="SERIAL NUMBER : 15 Digits">
                    </li>
                    <input type="hidden" name="device_name" value="fortest">
                    <input type="hidden" name="modelno" value="SMG001">
                    <input type="hidden" name="detail" value="SmartGrow">
                </ul>
                
            </div>
        </form>
        <button class="btn txt_14 tm50" id="device_register">Connect</button>
    </div>
    <!-- //device -->
</body>
{% endblock %}

device_management/templates/device_management/status.html
{% extends 'base_noti.html' %}
{% load static %}
{% block content %}
<body>
    <!-- dash_wrap -->
    <div class="dash_wrap footer_on">
        <!-- top_box -->
        <div class="top_box">
            <form action="">
                <ul>
                    <li>
                        <p class="input_tit">Farm Name</p>
                        <div class="input_box">

                            <input type="text" class="" value={{ farm.farm_name }} readonly>

                        </div>
                    </li>
                    <li>
                        <p class="input_tit">Crop Group</p>
                        <div class="input_box">

                            <input type="text" value={{ plant.crop_name }} readonly>

                        </div>
                    </li>
                    <li>
                        <p class="input_tit">Farm Capacity</p>
                        <div class="input_box plants_box">
                            <input type="text" value="{{ farm.farm_capacity }}" readonly>
                            <span>Plants</span>
                        </div>
                    </li>
                </ul>
            </form>
        </div>
        <!-- //top_box -->
        <div class="cont">
            <!-- tab_ul -->
            <ul class="tab_ul clear">
                <li class="on">
                    <a href="{% url 'device_management:status' farm.id %}" class="txt_medium">Status</a>
                </li>
                <li>
                    <a href="{% url 'device_management:history_detail' device_info.device_serial farm.id plant.id %}" class="txt_medium">History</a>
                </li>
                <li>
                    <a href="{% url 'device_management:device_control' device_info.device_serial farm.id %}" class="txt_medium">Control</a>
                </li>
            </ul>
            <!-- //tab_ul -->
            <div class="inner_box tank_box">
                <h2 class="title bold">Reservoir Tank</h2>
                <div class="">
                    <div class="left_graph"></div>
                    <div class="right_txt">
                        <p class="txt_medium"><img src={% static "images/img_warter.png" %} alt="warter image">Water Level</p>
                        <ul class="clear tp8">
                            <li class="fl rm20">Temp {{ grow_param.temparature }}</li>
                            <li class="fl rm20">PH {{ grow_param.ph }}</li>
                            <li class="fl rm20">EC {{ grow_param.ec }}</li>
                            <li class="fl">DO {{ grow_param.do }}</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="inner_box">
                <h2 class="title bold">Air</h2>
                <ul class="air_ul">
                    <li>
                        <h5 class="">Temp</h5>
                        <p class="">{{ grow_param.temparature }}˚F</p>
                    </li>
                    <li>
                        <h5 class="">Humidity</h5>
                        <p class="">{{ grow_param.humidity }}%</p>
                    </li>
                    <li>
                        <h5 class="">CO2</h5>

                        <p class="">{{grow_param.co2}}</p>

                        

                    </li>
                </ul>
            </div>
            <div class="inner_box">
                <h2 class="title bold">Nutrient Level - Fertigation Device</h2>
                <ul class="level_ul clear">
                    <li class="fl">
                        <h5 class="bold txt_gray88 txt_16">{{ grow_param.nutrientA }}%</h5>
                        <div class="bar_box">
                            <div class="bar" style="height: {{ grow_param.nutrientA }}%;"></div>
                        </div>
                        <p class="txt_gray88">A</p>
                    </li>
                    <li class="fl">
                        <h5 class="bold txt_gray88 txt_16">{{ grow_param.nutrientB }}%</h5>
                        <div class="bar_box">
                            <div class="bar" style="height: {{ grow_param.nutrientB }}%;"></div>
                        </div>
                        <p class="txt_gray88">B</p>
                    </li>
                    <li class="fl">
                        <h5 class="bold txt_gray88 txt_16">{{ grow_param.nutrientC }}%</h5>
                        <div class="bar_box">
                            <div class="bar" style="height: {{ grow_param.nutrientC }}%;"></div>
                        </div>
                        <p class="txt_gray88">C</p>
                    </li>
                    <li class="fl">
                        <h5 class="bold txt_gray88 txt_16">{{ grow_param.nutrientD }}%</h5>
                        <div class="bar_box">
                            <div class="bar" style="height: {{ grow_param.nutrientD }}%;"></div>
                        </div>
                        <p class="txt_gray88">D</p>
                    </li>
                </ul>
            </div>
            <div class="inner_box progress_box">
                <h2 class="title bold">Progress</h2>
                <div class="ul_box">
                    <ul class="top_ul" id="stage_bar">
                        <li class="">
                            <p class="txt_medium txt_gray_cc">Seedling</h5>
                            <p class="circle"></p>
                        </li>
                        <li class="">
                            <p class="txt_medium txt_gray_cc">Growing</h5>
                            <p class="circle"></p>
                        </li>
                        <li class="">
                            <p class="txt_medium txt_gray_cc">Maturing</h5>
                            <p class="circle"></p>
                        </li>
                        <li class="">
                            <p class="txt_medium txt_gray_cc">Hervest</h5>
                            <p class="circle"></p>
                        </li>
                    </ul>
                    <div class="bottom_ul_box">
                        <ul class="bottom_ul clear">
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                            <li class="fl"></li>
                        </ul>
                        <p style="width: 55%;" id="stage_colorline"></p>
                        <h6 class=" txt_gray66">{{rest_days}} Days left</h6>
                    </div>
                </div>
            </div>
            <div class="inner_box light_box">
                <h2 class="title bold">Light<img src={% static "images/img_sun.png" %} alt="sun image" class="lm3"></h2>
                <table class="tm27">
                    <caption>Light table</caption>
                    <colgroup>
                        <col style="width: 25%;">
                        <col style="width: 25%;">
                        <col style="width: 25%;">
                        <col style="width: 25%;">
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="txt_medium">Status</th>
                            <th class="txt_medium">Lux</th>
                            <th class="txt_medium">Hour/Day</th>
                            <th class="txt_medium">End time</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="">ON</td>

                            <td class="">{{grow_param.light_lux}}</td>

                            <td class="">{{ grow_param.light_hr }}</td>
                            <td class="">7 PM</td>
                        </tr>
                    </tbody>
                </table>
                <div class="tm20">
                    <div class="title_box">
                        <p class="txt_gray66">Daily progress</p>
                        <h5 class="bold txt_15">80%</h5>
                    </div>
                    <div class="bar_box">
                        <p class="bar" style="width:10%"></p>
                    </div>
                </div>
            </div>
            <div class="inner_box camera_box">
                <div class="clear">
                    <h2 class="title bold fl">Camera</h2>
                    <div class="fr toggle_box tx_c">
                        <label for="camera_toggle" class="toggle_btn">
                            <input type="checkbox" class="appearance dn" id="camera_toggle">
                            <span class="slider round"></span>
                        </label>
                        <p class="txt_gray88" style="display: none;">ON</p>
                        <p class="txt_gray88">OFF</p>
                    </div>
                </div>
                <div class="img_box"></div>
            </div>

            <button type="button" onclick="location.href='/twitter/post?farmid={{ farm.id }}'" class="share_btn">

                <img src={% static "images/ic_sharing.png" %} alt="sharing icon" class="fl">
                <span class=" fr">Share farm status</span>
            </button>
        </div>
    </div>

    <script>
        let life_stage_list = ['Seed Planting', 'Germination', 'Seedling', 'Growth', 'Hervest'];
        let line_width_list = ['0%', '5%', '10%', '30%', '100%'];
        let stage_colorline = document.querySelector("#stage_colorline");
        let text_cursor = document.querySelector("#stage_bar").children;
        for (let i=0; i<life_stage_list.length; i++){
            if(life_stage_list[i] == "{{ plant.life_stage }}"){
                stage_colorline.style.width = line_width_list[i];
                if (i < 3) text_cursor[0].classList.add("on");
                else if(i == 3) text_cursor[1].classList.add("on");
                else text_cursor[3].classList.add("on");
            }
        }
    </script>
</body>
{% endblock %}