config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('order/', include('order.urls')),
    path('twitter/', include('twitter_social.urls')),
    path('device_management/', include('device_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

device_management/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "device_management"

urlpatterns = [
    path('', views.device1, name='device1'),
    path('mypage',views.mypage, name='mypage'),
    path('control',views.control, name='control'),
    path('device',views.device, name='device'),
    path('device1', views.device1, name='device1'),
    path('device2', views.device2, name='device2'),
    path('device3', views.device3, name='device3'),
    path('device4', views.device4, name='device4'),
    path('device6', views.device6, name='device6'),

    path('device7', views.device7, name='device7'),
    path('create_plant_params', views.create_plant_params.as_view(), name='create_plant_params'),
    path('create_farm_info', views.create_farm_info.as_view(), name='Create_farm_info'),
    path('crop_info_registeration', views.crop_info_registeration.as_view(), name='crop_info_registeration'),

    path('status/<int:pk>', views.status, name='status'),

    path('my_page', views.mypage_status, name='my_page'),
    #path('crop_info_reg/<int:farm_info>', views.crop_info_reg_f, name='crop_info_reg'),
    path('crop_info_reg', views.crop_info_reg_f, name='crop_info_reg'),
    path('history_detail/<int:device_serial>/<int:farm_id>/<int:plant_id>',views.history_detail, name='history_detail'),
    
    path('device_control/<int:device_serial>/<int:farm_id>', views.goto_control_device, name="device_control"),
    path('send_action', views.GET_Interface_To_Device_Manual.as_view(), name="send_action"),
    path('catch_flying_status', views.get_mock_plant_status.as_view(), name="catch_flying_status"),
    path('compare', views.compare_currentState_with_default.as_view(), name="compare"),
    path('store_default_status',views.Store_Default_Status.as_view(), name="store_default_status"),
]

order/urls.py
from django.urls import path
from . import views
from .views import OrderCreate, AddCart, modify_cart

urlpatterns = [
    path('create/', OrderCreate.as_view()),
    path('addcart/', AddCart.as_view()),
    path('complete/',OrderCreate.as_view(), name='ordercomplete'),
    path('orderlist/<int:pk>',views.order_list, name='order_list'),
    path('cart/<int:pk>',views.cart_list, name='cartlist'),
    path('cart/modify/<int:pk>', views.modify_cart,name='modifycart'),
    path('payment/',views.payment, name='payment'),
    path('payment/complete',views.cart_to_buy, name='cartbuy')
]

twitter_social/urls.py
from django.urls import path
from .views import TwitterShare, TwitterPost, TwitterGet, TwitterBackground
urlpatterns = [
    path("share/", TwitterShare, name="twitter-share"),
    path("post/", TwitterPost, name="twitter-post"),
    path("get/<int:pk>/", TwitterGet, name="twitter-get"),
    path("background/", TwitterBackground, name="twitter-background"),
]

twitter_social/models.py
from django.db import models

# Create your models here.

twitter_social/views.py
from django.shortcuts import render, redirect
from .tweepy import tweet_scrap
from .data_share import parameter_send, parameter_get
from .macro import background_posting
from users.models import Users
from device_management.models import Device_Info, Farm_Info, Plant_Info, Growth_Params
from device_management.forms import Growth_Params_Form

def TwitterShare(request):
    # category를 나눌 수 있음
    user = Users.objects.get(email=request.user.email)
    content = {'user' : user}
    return render(request, 'twitter_share.html', content)

def TwitterPost(request):
    search_words = ["#krishian_1_0_0"]
    category = request.GET.get('category', None)
    farm_id = request.GET.get('farmid', None)
    if category is not None:
        search_words.append('#'+category)
    tweet_info = tweet_scrap(search_words)
    if farm_id is not None:
        farm = Farm_Info.objects.get(id=farm_id)
        plant = Plant_Info.objects.get(farm_info=farm)
        grow_param = Growth_Params.objects.filter(plant_info=plant)
        if grow_param:
            grow_param = grow_param[len(grow_param) - 1]  # not allow negative indexing
        else:
            grow_param = None
        data_text = parameter_send(grow_param, farm.farm_name)
    else:
        data_text = ''
    content = {
        "tweet_info": tweet_info,
        "data_text": data_text,
    }
    return render(request, 'twitter_post.html', content)

def TwitterGet(request, pk):
    #Get Farm Info and Choose Farm
    user = request.user
    try:
        device_info = Device_Info.objects.filter(device_user=user)[0]
    except:
        return redirect('device_management:device1')
    print(device_info)
    farm_list = Farm_Info.objects.filter(device_info=device_info)

    search_words = ["#krishian_1_0_0"]
    tweet_info = tweet_scrap(search_words)
    for tweet in tweet_info:
        if tweet["id"] == pk:
            gp = parameter_get(tweet["text"])
            break
    if gp:
        print(gp)
    return render(request, 'twitter_http_post.html', {'gp': gp,
                                                      'farm_list': farm_list})

def TwitterBackground(request):
    background_posting()
    return redirect('twitter-share')

twitter_social/templates/twitter_http_post.html
{% extends 'base_back_noti.html' %}
{% load static %}
{% block content %}
<body>
    <header class="header" style="background-color: #1DA1F2">
        <strong style="margin-bottom: 15px; font-size : 20px;">
            <a href="javascript:" class="txt_white txt_18">Choose Your Farm</a>
        </strong>
    </header>
    <br>
    <br>
    {% for farm in farm_list %}
    <form action={% url 'device_management:status' farm.id %} method="post">
        {% csrf_token %}
        <input type="hidden" name="germination_time" value={{ gp.germination_time }}>
        <input type="hidden" name="seeding_ec" value={{ gp.seeding_ec }}>
        <input type="hidden" name="ec" value={{ gp.ec }}>
        <input type="hidden" name="progress_date" value={{ gp.progress_date }}>
        <input type="hidden" name="temparature" value={{ gp.temparature }}>
        <input type="hidden" name="ph" value={{ gp.ph }}>
        <input type="hidden" name="humidity" value={{ gp.humidity }}>
        <input type="hidden" name="light_hr" value={{ gp.light_hr }}>
        <input type="hidden" name="nutrientA" value={{ gp.nutrientA }}>
        <input type="hidden" name="nutrientB" value={{ gp.nutrientB }}>
        <input type="hidden" name="nutrientC" value={{ gp.nutrientC }}>
        <input type="hidden" name="nutrientD" value={{ gp.nutrientD }}>
        <input type="hidden" name="light_lux" value={{ gp.light_lux }}>
        <input type="hidden" name="do" value={{ gp.do }}>
        <input type="hidden" name="co2" value={{ gp.co2 }}>
        <button type="submit" class="btn btn-primary">farm name : {{ farm.farm_name }}</button>
    </form>
        <br>
    {% endfor %}
</body>
{% endblock %}

twitter_social/templates/twitter_post.html
{% extends 'base_back_noti.html' %}
{% load static %}
{% block content %}
<body>
    <header class="header" style="background-color: #1DA1F2">
        <strong style="margin-bottom: 15px; font-size : 20px;">
            <a href="javascript:" class="txt_white txt_18">Feed</a>
        </strong>
        <a href="https://twitter.com/intent/tweet?button_hashtag=krishian_1_0_0&ref_src=twsrc%5Etfw"
                class="twitter-hashtag-button" id="twitter-share-btn" data-size="large"
                data-text="{{ data_text }}" data-lang="en" data-show-count="false">
        </a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </header>
    <div class="twit_form">
        <button type="button" onclick="location.href = '/twitter/post/'">All</button>
        <button type="button" onclick="location.href = '/twitter/post?category=crop'">Crop</button>
        <button type="button" onclick="location.href = '/twitter/post?category=cabbage'">Cabbage</button>
    </div>
    <div style="margin-left : 30px">
    {% for tweet in tweet_info %}
        <blockquote class="twitter-tweet">
            <a href="https://twitter.com/uQG1Y1vYu2RGFzU/status/{{ tweet.post_id }}"></a>
        </blockquote>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        <button type="button" onclick="location.href = '/twitter/get/{{ tweet.id }}/'" class="twit_btn bm30">
            Get parameter Tweet Number : {{ tweet.id }}
        </button>
    {% endfor %}
    </div>
</body>
{% endblock %}

twitter_social/templates/twitter_share.html
{% extends 'base_back_noti.html' %}
{% load static %}
{% load socialaccount %}
{% block content %}
<body>
    <!-- //header -->
    <div class="menu_wrap footer_on tx_c">
        <a href="{% provider_login_url 'twitter' %}">
            <button type="button" class="twit_btn tm50">
            <img src="{% static "images/ic_twitter_w.png" %}" alt="twitter icon">
            Log in with twitter
            </button>
        </a>
        <p class="tm50 txt_black33"><span class="txt_medium">Krishian</span> will receive:<br>Your photos, videos and timeline post.</p>
        <div class="edit_box">
            <a href="https://twitter.com/intent/tweet?button_hashtag=krishian_1_0_0&ref_src=twsrc%5Etfw" >
                Edit This
            </a>
        </div>
        <button type="button" onclick="location.href = '/twitter/post/'" class="conti_btn">Continue as <span class="txt_medium">{{ user.email }}</span></button>
    </div>
    <!-- footer_gnb -->
</body>
{% endblock %}